# Generated by Django 2.2.5 on 2019-11-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_auto_20191106_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='mesg_id',
            new_name='mesg',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='last_msg_id',
            new_name='last_msg',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='chat_id',
            new_name='chat',
        ),
        migrations.AlterField(
            model_name='member',
            name='new_mesg',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Is there new message in the chat?'),
        ),
    ]
