# Generated by Django 2.2.5 on 2019-11-18 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0003_auto_20191113_1300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='new_mesg',
            new_name='new_msg',
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Message sender'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='last_msg',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='chats.Message', verbose_name='Last read message'),
        ),
    ]
